name: infinite_lazy_grid
description: "infinitely scrollable and zoomable grid layout with lazy loading capabilities."
version: 1.0.0
homepage: https://github.com/ruinivist/infinite_lazy_grid

environment:
    sdk: ^3.8.1
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter
    uuid: ^4.5.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    shaders:
        - shaders/dot_grid.frag
